// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_service.proto

package com.eventbrite.eventservice;

public interface UpdateEventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.eventbrite.eventservice.UpdateEventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string eventName = 2;</code>
   * @return The eventName.
   */
  java.lang.String getEventName();
  /**
   * <code>string eventName = 2;</code>
   * @return The bytes for eventName.
   */
  com.google.protobuf.ByteString
      getEventNameBytes();

  /**
   * <code>string eventDescription = 3;</code>
   * @return The eventDescription.
   */
  java.lang.String getEventDescription();
  /**
   * <code>string eventDescription = 3;</code>
   * @return The bytes for eventDescription.
   */
  com.google.protobuf.ByteString
      getEventDescriptionBytes();

  /**
   * <code>string updated = 4;</code>
   * @return The updated.
   */
  java.lang.String getUpdated();
  /**
   * <code>string updated = 4;</code>
   * @return The bytes for updated.
   */
  com.google.protobuf.ByteString
      getUpdatedBytes();
}
