// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_service.proto

package com.eventbrite.eventservice;

public interface GetEventsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.eventbrite.eventservice.GetEventsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
