// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_service.proto

package com.eventbrite.eventservice;

public final class EventServiceOuterClass {
  private EventServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_eventbrite_eventservice_CreateEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_eventbrite_eventservice_CreateEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_eventbrite_eventservice_CreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_eventbrite_eventservice_CreateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_eventbrite_eventservice_UpdateEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_eventbrite_eventservice_UpdateEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_eventbrite_eventservice_UpdateEventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_eventbrite_eventservice_UpdateEventResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_eventbrite_eventservice_GetEventsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_eventbrite_eventservice_GetEventsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_eventbrite_eventservice_GetEventsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_eventbrite_eventservice_GetEventsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023event_service.proto\022\033com.eventbrite.ev" +
      "entservice\"M\n\022CreateEventRequest\022\n\n\002id\030\001" +
      " \001(\t\022\021\n\teventName\030\002 \001(\t\022\030\n\020eventDescript" +
      "ion\030\003 \001(\t\"Z\n\016CreateResponse\022\n\n\002id\030\001 \001(\t\022" +
      "\021\n\teventName\030\002 \001(\t\022\030\n\020eventDescription\030\003" +
      " \001(\t\022\017\n\007created\030\004 \001(\t\"M\n\022UpdateEventRequ" +
      "est\022\n\n\002id\030\001 \001(\t\022\021\n\teventName\030\002 \001(\t\022\030\n\020ev" +
      "entDescription\030\003 \001(\t\"_\n\023UpdateEventRespo" +
      "nse\022\n\n\002id\030\001 \001(\t\022\021\n\teventName\030\002 \001(\t\022\030\n\020ev" +
      "entDescription\030\003 \001(\t\022\017\n\007updated\030\004 \001(\t\"\036\n" +
      "\020GetEventsRequest\022\n\n\002id\030\001 \001(\t\"L\n\021GetEven" +
      "tsResponse\022\n\n\002id\030\001 \001(\t\022\021\n\teventName\030\002 \001(" +
      "\t\022\030\n\020eventDescription\030\003 \001(\t2\337\002\n\014EventSer" +
      "vice\022m\n\013CreateEvent\022/.com.eventbrite.eve" +
      "ntservice.CreateEventRequest\032+.com.event" +
      "brite.eventservice.CreateResponse\"\000\022r\n\013U" +
      "pdateEvent\022/.com.eventbrite.eventservice" +
      ".UpdateEventRequest\0320.com.eventbrite.eve" +
      "ntservice.UpdateEventResponse\"\000\022l\n\tGetEv" +
      "ents\022-.com.eventbrite.eventservice.GetEv" +
      "entsRequest\032..com.eventbrite.eventservic" +
      "e.GetEventsResponse\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_eventbrite_eventservice_CreateEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_eventbrite_eventservice_CreateEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_eventbrite_eventservice_CreateEventRequest_descriptor,
        new java.lang.String[] { "Id", "EventName", "EventDescription", });
    internal_static_com_eventbrite_eventservice_CreateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_eventbrite_eventservice_CreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_eventbrite_eventservice_CreateResponse_descriptor,
        new java.lang.String[] { "Id", "EventName", "EventDescription", "Created", });
    internal_static_com_eventbrite_eventservice_UpdateEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_eventbrite_eventservice_UpdateEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_eventbrite_eventservice_UpdateEventRequest_descriptor,
        new java.lang.String[] { "Id", "EventName", "EventDescription", });
    internal_static_com_eventbrite_eventservice_UpdateEventResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_eventbrite_eventservice_UpdateEventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_eventbrite_eventservice_UpdateEventResponse_descriptor,
        new java.lang.String[] { "Id", "EventName", "EventDescription", "Updated", });
    internal_static_com_eventbrite_eventservice_GetEventsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_eventbrite_eventservice_GetEventsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_eventbrite_eventservice_GetEventsRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_eventbrite_eventservice_GetEventsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_eventbrite_eventservice_GetEventsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_eventbrite_eventservice_GetEventsResponse_descriptor,
        new java.lang.String[] { "Id", "EventName", "EventDescription", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
